name: babeld-sabdfl # should land upstream and become babeld
version: git
summary: Babel is a loop-avoiding distance-vector routing protocol
base: core18
description: |
    Babel is a mesh-oriented routing protocol that is in the process of
    becoming an IETF standard.

grade: stable
confinement: strict

apps:
  babeld:
    daemon: simple
    command: launch.sh
    plugs: [ network, network-bind, network-control, firewall-control ]

parts:
  launch:
    plugin: dump
    source: launcher/
  babeld:
    # See 'snapcraft plugins'
    plugin: make
    build-packages: [ build-essential ]
    artifacts:
      - babeld
      - launch.sh
