name: babeld-sabdfl # should land upstream and become babeld
version: '1.8.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Babel is a loop-avoiding distance-vector routing protocol
description: |
    Babel is a mesh-oriented routing protocol that is in the process of
    becoming an IETF standard.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  babeld:
    daemon: forking
    command: bin/babeld

parts:
  babeld:
    # See 'snapcraft plugins'
    plugin: make
